# This is where you define the greater picture.
# This is the house.
version: '3'
services:
  frontend: #name of your service
    build: ./angular # specify the directory of the Dockerfile
    ports:
      - "4200:4200" #specify ports forwarding
    links:
      - backend # link this service to the database service
    volumes: # Map this folder to /usr/src/app in the container(as defined by WORKDIR)
      - ./angular:/usr/src/app
    depends_on:
      - backend
  backend:
    build: ./express
    ports:
      - "3000:3000" #specify ports forwarding
    links:
      - database # link this service to the database service
    volumes:
      - ./express/:/usr/src/app
    depends_on:
      - database
  database:
    image: mongo
